name: Deploy Azure Media Services FaceRedaction solution

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURECREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
     
    steps:
      - uses: actions/checkout@v2
        
      - name: Read Environment file
        id: dotenv
        uses: falti/dotenv-action@v0.2.5
        with:
          path: "./VideoAnalytics/FaceRedactorEventBased/.env"
       
      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
            pushd './VideoAnalytics/FaceRedactorEventBased/AzureFunction'
            python -m pip install --upgrade pip
            pip install -r requirements.txt --target=".python_packages/lib/site-packages"
            popd
    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure resources using Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion:  2.21.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/AzureServicesProvisioning/deploy_resources.azcli
            $GITHUB_WORKSPACE/AzureServicesProvisioning/deploy_resources.azcli
        env:
            SOLUTION_NAME: ${{ steps.dotenv.outputs.SOLUTION_NAME }}
            RESOURCE_GROUP: ${{ steps.dotenv.outputs.RESOURCE_GROUP }}
            LOCATION: ${{ steps.dotenv.outputs.LOCATION }}
            SUBSCRIPTION_ID: ${{ steps.dotenv.outputs.SUBSCRIPTION_ID }}
        
      - name: Deploy Azure Function code
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: "${{ steps.dotenv.outputs.SOLUTION_NAME}}functionapp"
          package: ./VideoAnalytics/FaceRedactorEventBased/AzureFunction
          respect-funcignore: true
          
      - name: Configure Azure resources using Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion:  2.21.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/AzureServicesProvisioning/configure_resources.azcli
            $GITHUB_WORKSPACE/AzureServicesProvisioning/configure_resources.azcli
        env:
            SOLUTION_NAME: ${{ steps.dotenv.outputs.SOLUTION_NAME }}
            RESOURCE_GROUP: ${{ steps.dotenv.outputs.RESOURCE_GROUP }}
            LOCATION: ${{ steps.dotenv.outputs.LOCATION }}
            SUBSCRIPTION_ID: ${{ steps.dotenv.outputs.SUBSCRIPTION_ID }}
